name: lastburger
version: 1.0.0+1
publish_to: none
description: Last Burger.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^3.0.1
  lottie: ^1.3.0
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^3.2.1
  firebase_storage: ^10.3.1
  firebase_image: ^1.1.1
  firebase: ^9.0.3
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/img/
    - assets/logo/
    - assets/lotties/
 

      
          

